/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.PhieuOrderDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.PhieuOrder;
import model.UsedSelectionFood;

/**
 *
 * @author Admin
 */
public class GDXacNhanOrder extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form ConfirmOrderFrm
     */
    DefaultTableModel model6;
    private static PhieuOrder phieuOrder;
    public GDXacNhanOrder(PhieuOrder phieuOrder) {
        initComponents();
        this.setLocationRelativeTo(null);
        model6 = (DefaultTableModel)tblResult.getModel();
        btnXacNhan.addActionListener(this);
        btnHuy.addActionListener(this);
        btnTiepTuc.addActionListener(this);
        
        this.phieuOrder = phieuOrder;
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbKhach = new javax.swing.JLabel();
        lbBan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        txtKhach = new javax.swing.JTextField();
        txtBan = new javax.swing.JTextField();
        btnXacNhan = new javax.swing.JButton();
        btnTiepTuc = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        txtTotalPrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbKhach.setText("Khách hàng");

        lbBan.setText("Bàn");

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblResultMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblResult);

        txtKhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKhachActionPerformed(evt);
            }
        });

        btnXacNhan.setText("Xác nhận");

        btnTiepTuc.setText("Tiếp tục");

        btnHuy.setText("Hủy");

        jLabel1.setText("Tổng tiền");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbKhach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(51, 51, 51)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtKhach, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                        .addComponent(txtBan))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnXacNhan)
                                .addGap(99, 99, 99)
                                .addComponent(btnTiepTuc)
                                .addGap(127, 127, 127)
                                .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbKhach)
                    .addComponent(txtKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBan)
                    .addComponent(txtBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXacNhan)
                    .addComponent(btnTiepTuc)
                    .addComponent(btnHuy))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKhachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKhachActionPerformed

    private void tblResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultMouseClicked
        // TODO add your handling code here:
        int row = tblResult.getSelectedRow();
        btnSelectClicked(row);
    }//GEN-LAST:event_tblResultMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GDXacNhanOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GDXacNhanOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GDXacNhanOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GDXacNhanOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GDXacNhanOrder(phieuOrder).setVisible(true);
            }
        });
    }
    public void btnConfirmClick(){
        try {
            PhieuOrderDAO phieuDAO = new PhieuOrderDAO();
                Date date = new Date();
                SimpleDateFormat  formatter = new SimpleDateFormat("dd-M-yyyy hh:mm:ss");
                String thoigian = formatter.format(date);
                phieuOrder.setThoigian(thoigian);
            
                int ok = phieuDAO.savePhieuOrder(phieuOrder);
                if(ok>=0){
                    JOptionPane.showMessageDialog(rootPane,"Gọi món thành công!");
                }
                else{
                    JOptionPane.showMessageDialog(rootPane,"Gọi món thất bại!");
                }
                new GDNVOrder().setVisible(true);
                this.dispose();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
    public void btnTiepTucClick(){
        new GDTimMon(phieuOrder).setVisible(true);
        this.dispose();
            
    }
    public void btnCancelClick(){
        new GDNVOrder().setVisible(true);
        this.dispose();
    }
    public void btnSelectClicked(int i){
     
            try {
                int response = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa món này không?", "Xóa món",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (response == JOptionPane.NO_OPTION) {
                    fillTable();
                } else if (response == JOptionPane.YES_OPTION) {
                    phieuOrder.getUsedSelectionFood().remove(i);
                    fillTable();
                }
                
            } catch (NullPointerException e) {
            }
    }
    @Override
    public void actionPerformed(ActionEvent ae) {
        JButton btn = (JButton)ae.getSource();
        if(btn.equals(btnXacNhan)){
            btnConfirmClick();
        }
        else if(btn.equals(btnHuy)){
            btnCancelClick();
        }
        else if(btn.equals(btnTiepTuc)){
            btnTiepTucClick();
        }
    
    }
    public void fillTable() {// hien thi ket qua
        model6.setRowCount(0);
        model6.setColumnIdentifiers(new Object[]{"STT","tên", "kiểu", "giá","số lượng","thành tiền"}); 
        txtKhach.setEditable(false);
        txtBan.setEditable(false);
        txtTotalPrice.setEditable(false);
        txtKhach.setText(phieuOrder.getBooking().getClient().getName());
        txtBan.setText(phieuOrder.getBooking().getTable().getName());
        int i = 0;
        ArrayList<UsedSelectionFood> listUsedSelectionFood = new ArrayList<UsedSelectionFood>();
        listUsedSelectionFood = phieuOrder.getUsedSelectionFood();
        float totalPrice = 0;
        for (UsedSelectionFood usf : listUsedSelectionFood) {
            if(usf.getSelectionFood().getCombo()!=null){
            model6.addRow(new Object[]{i+1,usf.getSelectionFood().getCombo().getName(),usf.getSelectionFood().getCombo().getType(),usf.getSelectionFood().getCombo().getPrice(),usf.getQuantity(),usf.getQuantity()*usf.getSelectionFood().getCombo().getPrice()});
                i++;
                totalPrice +=(usf.getQuantity()*usf.getSelectionFood().getCombo().getPrice());
            }
            if(usf.getSelectionFood().getFood()!=null){
            model6.addRow(new Object[]{i+1,usf.getSelectionFood().getFood().getName(),usf.getSelectionFood().getFood().getType(),usf.getSelectionFood().getFood().getPrice(),usf.getQuantity(),usf.getQuantity()*usf.getSelectionFood().getFood().getPrice()});
                i++;
                totalPrice +=(usf.getQuantity()*usf.getSelectionFood().getFood().getPrice());
            }
        }
        txtTotalPrice.setText(String.valueOf(totalPrice));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnTiepTuc;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBan;
    private javax.swing.JLabel lbKhach;
    private javax.swing.JTable tblResult;
    private javax.swing.JTextField txtBan;
    private javax.swing.JTextField txtKhach;
    private javax.swing.JTextField txtTotalPrice;
    // End of variables declaration//GEN-END:variables
}
