/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Admin
 */

import controller.MemberDAO;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
public class LoginFrm extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form GDLogin
     */
    public LoginFrm() {
        initComponents();
        this.setLocationRelativeTo(null);
        btnLogin.addActionListener(this);
        btnReset.addActionListener(this);
        btnCancel.addActionListener(this);
        jLabel4.setIcon(new ImageIcon("Login_nen.jpg")); 
        ImageIcon icon = new ImageIcon("Ok.png");
        btnLogin.setIcon(icon);
        ImageIcon icon1 = new ImageIcon("Button_cancel.png");
        btnCancel.setIcon(icon1);
        ImageIcon icon2 = new ImageIcon("Button_reset.png");
        btnReset.setIcon(icon2);
//        setSize(700,400);
//        setLocation(600, 300);
        setSize(900,700);
        setLocation(600, 300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPassWord = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxRole = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 50, 90, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 140, 80, 20);
        getContentPane().add(txtUser);
        txtUser.setBounds(370, 40, 210, 40);
        getContentPane().add(txtPassWord);
        txtPassWord.setBounds(370, 120, 210, 40);

        btnLogin.setForeground(new java.awt.Color(255, 0, 0));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(120, 370, 130, 50);

        btnReset.setForeground(new java.awt.Color(255, 0, 0));
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset);
        btnReset.setBounds(410, 370, 120, 50);

        btnCancel.setForeground(new java.awt.Color(255, 0, 0));
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(680, 370, 120, 50);

        jLabel3.setText("Tình trạng kết nối");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 460, 101, 16);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Role");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(130, 230, 80, 20);

        cbxRole.setForeground(new java.awt.Color(255, 255, 255));
        cbxRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Manager", "Seller", "Receptionist", "Order" }));
        getContentPane().add(cbxRole);
        cbxRole.setBounds(370, 220, 210, 40);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 900, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed

    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cbxRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField txtPassWord;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
    public void btnLoginClick(){
        if(this.txtUser.getText().length()==0||String.valueOf(this.txtPassWord.getPassword()).length()==0){
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập thông tin tài khoản hoặc mật khẩu","Thông báo",1);
        }
        else{
            try {
                String user,pass,role;
                user = this.txtUser.getText();
                pass = String.valueOf(this.txtPassWord.getPassword());
                role = cbxRole.getSelectedItem().toString();
                MemberDAO md = new MemberDAO();
                int OK = md.login(user,pass,role);
                if(OK>0&&role.equals("Seller")){
                    //Đăng nhập thành công
                   new GDNVBanHang().setVisible(true);
                   this.setVisible(false);
                }
                else if(OK>0&&role.equals("Receptionist")){
                    //Đăng nhập thành công
                   new GDLeTan().setVisible(true);
                   this.setVisible(false);
                }
                else if(OK>0&&role.equals("Order")){
                    //Đăng nhập thành công
                   new GDNVOrder().setVisible(true);
                   this.setVisible(false);
                }
                else{
                    //Đăng nhập thất bại
                    JOptionPane.showMessageDialog(null, "Tài khoản hoặc mật khẩu không chính xác!","Thông báo",1);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e,"Thông báo",1);
            }
        }
    }
    public void btnResetClick(){
        this.txtUser.setText("");
        this.txtPassWord.setText("");
    }
    public void btnCancelClick(){
        if(JOptionPane.showConfirmDialog(null,"Bạn có chắc chắn muốn thoát không","Thông báo",2)==0){
            System.exit(0);
        }
    }
    @Override
    public void actionPerformed(ActionEvent ae) {
        JButton btn  = (JButton)ae.getSource();
        if(btn.equals(btnLogin)){
            btnLoginClick();
        }
        else if(btn.equals(btnReset)){
            btnResetClick();
        }
        else if(btn.equals(btnCancel)){
            btnCancelClick();
        }
    }

}
